Repository maple-labs/revenue-distribution-token, pull requests merged in 2022-03, with the labels that each got.

#42 feat: Use RDTTestBase (SC-5205)
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#43 feat: Use new test pattern for `deposit` and `mint` (SC-5205)
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#44 feat: Use new test pattern for `depositWithPermit` and `mintWithPermit` (SC-5205)
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#45 feat: User new test pattern for `withdraw` and `redeem` caller not owner (SC-5205)
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#47 feat: Use new test pattern with `withdraw` and `redeem` (SC-5205)
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#48 chore: Remove redundant successful tests
  README.md
  contracts/test/Invariants.t.sol
  contracts/test/RevenueDistributionToken.t.sol
  invariant-test.sh
Labels: Status: Ready for Review, Priority: High

#49 chore: Segregate tests and remove redundant internal test functions
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#50 chore: Reorder tests alphabetically
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#51 chore: Move tests and make them public
  contracts/test/RDTGetters.t.sol
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#52 chore: Formatting sweep
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#53 fix: Virtual Overriden Setups
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: High

#54 fix: C4 - adjust comment on precision (SC-5355)
  contracts/RevenueDistributionToken.sol
Labels: Status: Ready for Review

#55 fix: C4 - remove todo comments (SC-5354)
  contracts/RevenueDistributionToken.sol
Labels: Status: Ready for Review

#56 fix: Remove redundant type casts to address (SC-5347)
  contracts/RevenueDistributionToken.sol
Labels: Status: Ready for Review, Priority: Low

#59 fix: C4 - Cache state variables in totalAssets (SC - 5379)
  contracts/RevenueDistributionToken.sol
Labels: Status: Ready for Review

#62 fix: Reuse infinite approval functionality from `ERC20` (SC-5348)
  contracts/RevenueDistributionToken.sol
  contracts/test/RevenueDistributionToken.t.sol
Labels: Status: Ready for Review, Priority: Medium
